### ISSUE TITLE
New developer onboarding needs communication method

### ISSUE THREAD

**Issue by dsmegha** [stom01/fittfu#18]
Hey @stom01 and @jatkins23 . Would love to contribute to this project. Could I have a fittfu username/password combination to check out the site at heroku?

**Comment by skylertom** [comment]
Hi @dsmegha,
Thank you for your interest in this project (and I am sorry for the late response). This project is built for the ultimate frisbee team at Tufts, and we are limiting developers to Tufts students and alumni associated with the ultimate frisbee team.
